### ISSUE TITLE
Installer le module Turtle avce Calysto

### ISSUE THREAD

**Issue by capytale** [capytale/capytale#10]
https://jupyter.brynmawr.edu/services/public/dblank/Experiments/Calysto%20Turtle%20Graphics.ipynb

avec pip install calysto

**Comment by louvois** [comment]
C'est fait sur jupyterhub. Il faut vérifier que si ça fonctionne avant de le propager sur les nbhostings

**Comment by capytale** [comment]
Cela fonctionne.
On peut le déployer sur les nbhostings.
Merci
