### ISSUE TITLE
Noyau Ocaml

### ISSUE THREAD

**Issue by capytale** [capytale/capytale#2]
Il serait intéressant pour les enseignants (noatmment en prépa) d'installer le noyau Ocaml :

- https://github.com/jupyter/jupyter/wiki/Jupyter-kernels
- http://pascal.ortiz.free.fr/contents/autres/jupyter\_ocaml/jupyter\_ocaml.html

**Comment by louvois** [comment]
L'intégration du Noyai Ocaml version 4.08  est achevée dans l'environnement de tes: OK

**Comment by louvois** [comment]
![2020-02-12_003025](https://user-images.githubusercontent.com/6781247/74289305-f99ef500-4d2e-11ea-9cae-575c82ad6f94.png)

**Comment by louvois** [comment]
Ocaml intégré désormais dans l'image docker "nbhosting/scipy-notebooks" de Thierry

**Comment by louvois** [comment]
le noyau Ocaml sur les 4 nbhostings de prod
