### ISSUE TITLE
Éléments manquants sur l'interface élève

### ISSUE THREAD

**Issue by capytale** [capytale/capytale#3]
Il faudrait modifier l'image Jupyter pour nbhosting afin de
1. permettre la modification des cellules de texte par les élèves
2. proposer une interface en français

**Comment by louvois** [comment]
L'interface en Français, c'est possible. Il fallait modifier l'image d'origine et ajouter des paramètres supplémentaires pour le lancer.

**Comment by louvois** [comment]
modification réussie de l'image d'origine "nbhosting/scipy-notebook"
- Interface en Français 
- la modification des cellules de texte par les élèves
- restauration du menu original

![2020-02-13_002325](https://user-images.githubusercontent.com/6781247/74387031-cecca380-4df7-11ea-9029-02baf421fd45.png)

**Comment by louvois** [comment]
L'interface élève ressemble désormais à l'interface d'origine de Thierry. L'élève ne devrait pas avoir de difficultés pour se retrouver.
